sudo: false
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master
#
# services:
#
# matrix:
#  include:
#    - os: linux

env:
   
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - mkdir -p $HOME/.mantid
#  - echo "default.facility=SNS" > $HOME/.mantid/Mantid.user.properties

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - export PYTHON_VERSION=2.7
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda config --add channels mcvine
  - conda config --add channels neutrons
  - conda config --add channels mantid
  - conda create -n testenv pip pytest pytest-cov python=PYTHON_VERSION numpy scipy matplotlib histogram ipywe mantid-framework=4
  - source activate testenv
  - python setup.py install
  - pip install coveralls
#  - pip install codecov

script:
   - travis_wait 60 py.test --cov=multiphonon tests
   - python examples/getdos-Al.py
   - python examples/getdos-Al-from-nparrs.py
# the following were run standalone but now all included in the cmd above.
#   - travis_wait 40 python tests/getdos_TestCase.py
#   - travis_wait 20 python tests/getdos_TestCase2.py
#   - travis_wait 20 python tests/ui/batch_TestCase.py

after_success:
   - coveralls

notifications:
  email:
    on_success: change
    on_failure: always
