package:
  name: multiphonon
  version: "0.1.3a2"

source:
  git_rev: 2to3
  git_url: https://github.com/sns-chops/multiphonon.git

requirements:
  build:
    - python
    - numpy
    - histogram
    - scipy

  run:
    - python
    - numpy
    - histogram
    - scipy
    - matplotlib
    - pytest
    - pyyaml
#    - mantid-framework
#    - ipywe

build:
  noarch: python
  script_env:

test:
  imports:
    - multiphonon

about:
  home: 
  license:
  license_file:
